In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Data_set/online_fraud/onlinefraud.csv')

In [ ]:
print(df.head())

   step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0  
3    C38997010         21182.0             0.0        1               0  
4  M1230701703             0.0             0.0        0               0  


In [ ]:
df.shape

(6362620, 11)

In [ ]:
df.describe()

step        amount  oldbalanceOrg  newbalanceOrig  \
count  6.362620e+06  6.362620e+06   6.362620e+06    6.362620e+06   
mean   2.433972e+02  1.798619e+05   8.338831e+05    8.551137e+05   
std    1.423320e+02  6.038582e+05   2.888243e+06    2.924049e+06   
min    1.000000e+00  0.000000e+00   0.000000e+00    0.000000e+00   
25%    1.560000e+02  1.338957e+04   0.000000e+00    0.000000e+00   
50%    2.390000e+02  7.487194e+04   1.420800e+04    0.000000e+00   
75%    3.350000e+02  2.087215e+05   1.073152e+05    1.442584e+05   
max    7.430000e+02  9.244552e+07   5.958504e+07    4.958504e+07   

       oldbalanceDest  newbalanceDest       isFraud  isFlaggedFraud  
count    6.362620e+06    6.362620e+06  6.362620e+06    6.362620e+06  
mean     1.100702e+06    1.224996e+06  1.290820e-03    2.514687e-06  
std      3.399180e+06    3.674129e+06  3.590480e-02    1.585775e-03  
min      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00  
25%      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00  
50%      1.327057e+05    2.146614e+05  0.000000e+00    0.000000e+00  
75%      9.430367e+05    1.111909e+06  0.000000e+00    0.000000e+00  
max      3.560159e+08    3.561793e+08  1.000000e+00    1.000000e+00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
 10  isFlaggedFraud  int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB


In [ ]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [ ]:
df.sample(10)

step      type     amount     nameOrig  oldbalanceOrg  \
2358176   190   PAYMENT    7603.67  C1725636525         416.00   
3561052   260   CASH_IN  213994.46   C313095548     1290848.66   
3856574   283  CASH_OUT   57945.17  C2009504578       42223.00   
1146543   131   PAYMENT    6193.44   C701763219           0.00   
4884586   348   CASH_IN   88014.20  C1741604279     2080435.12   
3223499   250   PAYMENT   13483.54   C332221543      181643.00   
4633294   330   CASH_IN   22231.33   C446805346      473317.55   
3310302   252   CASH_IN  131588.52  C1697474903       35787.00   
5173622   358  TRANSFER  346881.07   C613965801           0.00   
4629751   329   PAYMENT   51449.37  C1092738420      152954.00   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
2358176            0.00  M1002224320            0.00            0.00        0   
3561052      1504843.11  C1751454321       333425.38       119430.92        0   
3856574            0.00   C746785971            0.00        57945.17        0   
1146543            0.00   M363757277            0.00            0.00        0   
4884586      2168449.32  C1852959541       181627.72        93613.52        0   
3223499       168159.46  M1813459720            0.00            0.00        0   
4633294       495548.89  C1857685192       164457.00       142225.67        0   
3310302       167375.52  C1588480190            0.00            0.00        0   
5173622            0.00  C1286652031      1877769.30      2224650.37        0   
4629751       101504.63  M1399502706            0.00            0.00        0   

         isFlaggedFraud  
2358176               0  
3561052               0  
3856574               0  
1146543               0  
4884586               0  
3223499               0  
4633294               0  
3310302               0  
5173622               0  
4629751               0

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import mean_squared_error

# Assuming 'df' is your dataset and 'isFraud' is the target variable
X = df.drop('isFraud', axis=1)
y = df['isFraud']

# Identify categorical columns
categorical_cols = X.select_dtypes(include=['object']).columns

# Encode categorical features using Label Encoding (or use One-Hot Encoding)
for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale only numerical features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and train models
models = {'Logistic Regression': LogisticRegression()}

results = {}

for name, model in models.items():
    try:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred) # Calculate MSE
        results[name] = {
            'accuracy': accuracy,
            'mse': mse, # Store MSE in results
            'classification_report': classification_report(y_test, y_pred),
            'confusion_matrix': confusion_matrix(y_test, y_pred)
        }
        print(f"{name} - Accuracy: {accuracy}, MSE: {mse}") # Print MSE

    except Exception as e:
        print(f"Error training {name}: {e}")

for name, result in results.items():
    print(f"\n{name} Results:")
    print(f"Accuracy: {result['accuracy']}")
    print(f"MSE: {result['mse']}") # Print MSE from results
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}")

Logistic Regression - Accuracy: 0.9991897991707819, MSE: 0.0008102008292181522

Logistic Regression Results:
Accuracy: 0.9991897991707819
MSE: 0.0008102008292181522
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.91      0.41      0.56      1620

    accuracy                           1.00   1272524
   macro avg       0.95      0.70      0.78   1272524
weighted avg       1.00      1.00      1.00   1272524

Confusion Matrix:
[[1270835      69]
 [    962     658]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming 'df' is your dataset and 'isFraud' is the target variable
X = df.drop('isFraud', axis=1)
y = df['isFraud']

# Identify categorical columns
categorical_cols = X.select_dtypes(include=['object']).columns

# Encode categorical features using Label Encoding (or use One-Hot Encoding)
for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale only numerical features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and train models
models = {'Decision Tree': DecisionTreeClassifier()}

results = {}

for name, model in models.items():
    try:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred) # Calculate MSE
        results[name] = {
            'accuracy': accuracy,
            'mse': mse, # Store MSE in results
            'classification_report': classification_report(y_test, y_pred),
            'confusion_matrix': confusion_matrix(y_test, y_pred)
        }
        print(f"{name} - Accuracy: {accuracy}, MSE: {mse}") # Print MSE

    except Exception as e:
        print(f"Error training {name}: {e}")

for name, result in results.items():
    print(f"\n{name} Results:")
    print(f"Accuracy: {result['accuracy']}")
    print(f"MSE: {result['mse']}") # Print MSE from results
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}")

Decision Tree - Accuracy: 0.9996935224797332, MSE: 0.00030647752026680835

Decision Tree Results:
Accuracy: 0.9996935224797332
MSE: 0.00030647752026680835
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.89      0.86      0.88      1620

    accuracy                           1.00   1272524
   macro avg       0.95      0.93      0.94   1272524
weighted avg       1.00      1.00      1.00   1272524

Confusion Matrix:
[[1270733     171]
 [    219    1401]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming 'df' is your dataset and 'isFraud' is the target variable
X = df.drop('isFraud', axis=1)
y = df['isFraud']

# Identify categorical columns
categorical_cols = X.select_dtypes(include=['object']).columns

# Encode categorical features using Label Encoding (or use One-Hot Encoding)
for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale only numerical features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and train models
models = {'Random Forest': RandomForestClassifier()}

results = {}

for name, model in models.items():
    try:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred) # Calculate MSE
        results[name] = {
            'accuracy': accuracy,
            'mse': mse, # Store MSE in results
            'classification_report': classification_report(y_test, y_pred),
            'confusion_matrix': confusion_matrix(y_test, y_pred)
        }
        print(f"{name} - Accuracy: {accuracy}, MSE: {mse}") # Print MSE

    except Exception as e:
        print(f"Error training {name}: {e}")

for name, result in results.items():
    print(f"\n{name} Results:")
    print(f"Accuracy: {result['accuracy']}")
    print(f"MSE: {result['mse']}") # Print MSE from results
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}")

Random Forest - Accuracy: 0.9997100251154398, MSE: 0.00028997488456013404

Random Forest Results:
Accuracy: 0.9997100251154398
MSE: 0.00028997488456013404
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.99      0.78      0.87      1620

    accuracy                           1.00   1272524
   macro avg       0.99      0.89      0.94   1272524
weighted avg       1.00      1.00      1.00   1272524

Confusion Matrix:
[[1270889      15]
 [    354    1266]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming 'df' is your dataset and 'isFraud' is the target variable
X = df.drop('isFraud', axis=1)
y = df['isFraud']

# Identify categorical columns
categorical_cols = X.select_dtypes(include=['object']).columns

# Encode categorical features using Label Encoding (or use One-Hot Encoding)
for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale only numerical features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and train models
models = {'KNN': KNeighborsClassifier()}

results = {}

for name, model in models.items():
    try:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred) # Calculate MSE
        results[name] = {
            'accuracy': accuracy,
            'mse': mse, # Store MSE in results
            'classification_report': classification_report(y_test, y_pred),
            'confusion_matrix': confusion_matrix(y_test, y_pred)
        }
        print(f"{name} - Accuracy: {accuracy}, MSE: {mse}") # Print MSE

    except Exception as e:
        print(f"Error training {name}: {e}")

for name, result in results.items():
    print(f"\n{name} Results:")
    print(f"Accuracy: {result['accuracy']}")
    print(f"MSE: {result['mse']}") # Print MSE from results
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}")

KNN - Accuracy: 0.9991866558115996, MSE: 0.0008133441884003759

KNN Results:
Accuracy: 0.9991866558115996
MSE: 0.0008133441884003759
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.97      0.37      0.54      1620

    accuracy                           1.00   1272524
   macro avg       0.98      0.69      0.77   1272524
weighted avg       1.00      1.00      1.00   1272524

Confusion Matrix:
[[1270883      21]
 [   1014     606]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming 'df' is your dataset and 'isFraud' is the target variable
X = df.drop('isFraud', axis=1)
y = df['isFraud']

# Identify categorical columns
categorical_cols = X.select_dtypes(include=['object']).columns

# Encode categorical features using Label Encoding (or use One-Hot Encoding)
for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale only numerical features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and train models
models = {'Naive Bayes': GaussianNB()}

results = {}

for name, model in models.items():
    try:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred) # Calculate MSE
        results[name] = {
            'accuracy': accuracy,
            'mse': mse, # Store MSE in results
            'classification_report': classification_report(y_test, y_pred),
            'confusion_matrix': confusion_matrix(y_test, y_pred)
        }
        print(f"{name} - Accuracy: {accuracy}, MSE: {mse}") # Print MSE

    except Exception as e:
        print(f"Error training {name}: {e}")

for name, result in results.items():
    print(f"\n{name} Results:")
    print(f"Accuracy: {result['accuracy']}")
    print(f"MSE: {result['mse']}") # Print MSE from results
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}")

Naive Bayes - Accuracy: 0.9959419232957493, MSE: 0.004058076704250764

Naive Bayes Results:
Accuracy: 0.9959419232957493
MSE: 0.004058076704250764
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.04      0.10      0.06      1620

    accuracy                           1.00   1272524
   macro avg       0.52      0.55      0.53   1272524
weighted avg       1.00      1.00      1.00   1272524

Confusion Matrix:
[[1267195    3709]
 [   1455     165]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming 'df' is your dataset and 'isFraud' is the target variable
X = df.drop('isFraud', axis=1)
y = df['isFraud']

# Identify categorical columns
categorical_cols = X.select_dtypes(include=['object']).columns

# Encode categorical features using Label Encoding (or use One-Hot Encoding)
for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale only numerical features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and train models
models = {'XGBoost': XGBClassifier()}

results = {}

for name, model in models.items():
    try:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred) # Calculate MSE
        results[name] = {
            'accuracy': accuracy,
            'mse': mse, # Store MSE in results
            'classification_report': classification_report(y_test, y_pred),
            'confusion_matrix': confusion_matrix(y_test, y_pred)
        }
        print(f"{name} - Accuracy: {accuracy}, MSE: {mse}") # Print MSE

    except Exception as e:
        print(f"Error training {name}: {e}")

for name, result in results.items():
    print(f"\n{name} Results:")
    print(f"Accuracy: {result['accuracy']}")
    print(f"MSE: {result['mse']}") # Print MSE from results
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}")

XGBoost - Accuracy: 0.999775249818471, MSE: 0.00022475018152899278

XGBoost Results:
Accuracy: 0.999775249818471
MSE: 0.00022475018152899278
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.96      0.86      0.91      1620

    accuracy                           1.00   1272524
   macro avg       0.98      0.93      0.95   1272524
weighted avg       1.00      1.00      1.00   1272524

Confusion Matrix:
[[1270844      60]
 [    226    1394]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming 'df' is your dataset and 'isFraud' is the target variable
X = df.drop('isFraud', axis=1)
y = df['isFraud']

# Identify categorical columns
categorical_cols = X.select_dtypes(include=['object']).columns

# Encode categorical features using Label Encoding (or use One-Hot Encoding)
for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale only numerical features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and train models
models = {'SVM': SVC()}

results = {}

for name, model in models.items():
    try:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred) # Calculate MSE
        results[name] = {
            'accuracy': accuracy,
            'mse': mse, # Store MSE in results
            'classification_report': classification_report(y_test, y_pred),
            'confusion_matrix': confusion_matrix(y_test, y_pred)
        }
        print(f"{name} - Accuracy: {accuracy}, MSE: {mse}") # Print MSE

    except Exception as e:
        print(f"Error training {name}: {e}")

for name, result in results.items():
    print(f"\n{name} Results:")
    print(f"Accuracy: {result['accuracy']}")
    print(f"MSE: {result['mse']}") # Print MSE from results
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}")

SVM - Accuracy: 0.9992597389125863, MSE: 0.0007402610874136755

SVM Results:
Accuracy: 0.9992597389125863
MSE: 0.0007402610874136755
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       1.00      0.42      0.59      1620

    accuracy                           1.00   1272524
   macro avg       1.00      0.71      0.80   1272524
weighted avg       1.00      1.00      1.00   1272524

Confusion Matrix:
[[1270902       2]
 [    940     680]]
